#!/bin/bash
# Stamps the build with an identifiable version:
#   pubspec version -> 1.0.<commit-count>+<commit-count>  (integer versionCode)
#   lib/core/build_stamp.dart -> const buildSha ('<git-short>'), buildNumber
# Run before `flutter build`. Committed stamp files are regenerated each
# build so the app's Settings screen can answer "which build is this?"
set -euo pipefail
cd "$(dirname "$0")/.."

# Pin the count to the last NON-STAMP commit: counting HEAD chases its own
# tail (each stamp commit bumps the count, requiring another stamp).
# STAMP_BASE is the last real commit; if HEAD is itself a stamp commit,
# count its parent and mark the SHA with a '+' suffix.
STAMP_BASE=$(git log --format='%h %s' -1 HEAD)
if echo "$STAMP_BASE" | grep -q '^\w* Stamp build'; then
  SHA="$(git rev-parse --short HEAD)+"
  COUNT=$(($(git rev-list --count HEAD) - 1))
else
  SHA=$(git rev-parse --short HEAD)
  COUNT=$(git rev-list --count HEAD)
fi

python3 - "$SHA" "$COUNT" <<'PYEOF'
import sys, re
sha, count = sys.argv[1], sys.argv[2]

# pubspec: version line
p = 'pubspec.yaml'
s = open(p).read()
s = re.sub(r'^version: .*$', f'version: 1.0.{count}+{count}', s, count=1, flags=re.M)
open(p, 'w').write(s)

# generated stamp
stamp = f'''//! GENERATED by tool/stamp_version.sh — do not edit by hand.
/// Identifies the exact source revision of this build (shown in Settings).
library;

/// Git short SHA of the commit this build was made from.
const String buildSha = '{sha}';

/// Git commit count at build time (matches the Android versionCode).
const int buildNumber = {count};
'''
open('lib/core/build_stamp.dart', 'w').write(stamp)
print(f'stamped: 1.0.{count}+{count} ({sha})')
PYEOF
