//! GENERATED by tool/stamp_version.sh — do not edit by hand.
/// Identifies the exact source revision of this build (shown in Settings).
library;

/// Git short SHA of the commit this build was made from.
const String buildSha = 'bc67d84+';

/// Git commit count at build time (matches the Android versionCode).
const int buildNumber = 31;
